services:
  identity-server:
    build: 
        context: .
        dockerfile: IdentityServer_Dockerfile_Debug
    container_name: IdentityServer
    image: "identity-server-debug"
    ports:
      - "5001:5001"
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet OnlineShop.IdentityServer.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pass12345
    volumes:
      - D:/OnlineShop/localhost.pfx:/https/localhost.pfx:ro
      - D:/OnlineShop/localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
      - D:/OnlineShop/temp:/logs
  
  user-management-service:
      build:
          context: .
          dockerfile: UserManagementService_Dockerfile_Debug
      container_name: UserManagementService
      image: "user-management-service-debug"
      ports:
        - "5002:5002"
        - "5003:5003"
      entrypoint: /bin/sh -c "update-ca-certificates && dotnet OnlineShop.UserManagementService.dll"
      environment:
        - ASPNETCORE_URLS=https://+:5003;http://+:5002
        - ASPNETCORE_ENVIRONMENT=Docker
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
        - ASPNETCORE_Kestrel__Certificates__Default__Password=pass12345
      volumes:
        - D:/OnlineShop/localhost.pfx:/https/localhost.pfx:ro
        - D:/OnlineShop/localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
        - D:/OnlineShop/temp:/logs
      depends_on:
        - identity-server

  orders-service:
        build:
          context: .
          dockerfile: OrdersService_Dockerfile_Debug
        container_name: OrdersService
        image: "orders-service-debug"
        ports:
          - "5004:5004"
          - "5005:5005"
        entrypoint: /bin/sh -c "update-ca-certificates && dotnet OnlineShop.OrdersService.dll"
        environment:
          - ASPNETCORE_URLS=https://+:5005;http://+:5004
          - ASPNETCORE_ENVIRONMENT=Docker
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
          - ASPNETCORE_Kestrel__Certificates__Default__Password=pass12345
        volumes:
          - D:/OnlineShop/localhost.pfx:/https/localhost.pfx:ro
          - D:/OnlineShop/localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
          - D:/OnlineShop/temp:/logs
        depends_on:
          - identity-server

  articles-service:
        build:
          context: .
          dockerfile: ArticlesService_Dockerfile_Debug
        container_name: ArticlesService
        image: "articles-service-debug"
        ports:
          - "5006:5006"
          - "5007:5007"
        entrypoint: /bin/sh -c "update-ca-certificates && dotnet OnlineShop.ArticlesService.dll"
        environment:
          - ASPNETCORE_URLS=https://+:5007;http://+:5006
          - ASPNETCORE_ENVIRONMENT=Docker
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
          - ASPNETCORE_Kestrel__Certificates__Default__Password=pass12345
        volumes:
          - D:/OnlineShop/localhost.pfx:/https/localhost.pfx:ro
          - D:/OnlineShop/localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
          - D:/OnlineShop/temp:/logs
        depends_on:
          - identity-server

  api-service:
        build:
          context: .
          dockerfile: ApiService_Dockerfile_Debug
        container_name: ApiService
        image: "api-service-debug"
        ports:
          - "5008:5008"
          - "5009:5009"
        entrypoint: /bin/sh -c "update-ca-certificates && dotnet OnlineShop.ApiService.dll"
        environment:
          - ASPNETCORE_URLS=https://+:5009;http://+:5008
          - ASPNETCORE_ENVIRONMENT=Docker
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
          - ASPNETCORE_Kestrel__Certificates__Default__Password=pass12345
        volumes:
          - D:/OnlineShop/localhost.pfx:/https/localhost.pfx:ro
          - D:/OnlineShop/localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
          - D:/OnlineShop/temp:/logs
        depends_on:
          - identity-server
          - user-management-service
          - orders-service
          - articles-service


    
  
