GET https://localhost:5009/users/all
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVCMTg0RTI3MDg5RTVFRDU2OTJFOTcyNjU2NjVDNkQyIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE3MDQ3MzcyMjcsImV4cCI6MTcwNDc0MDgyNywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImNsaWVudF9pZCI6InRlc3QuY2xpZW50IiwianRpIjoiQ0VEQTFCNUE2MUY3OUZFQTAzRjQ1MjQxNzZCRDc2M0QiLCJpYXQiOjE3MDQ3MzcyMjcsInNjb3BlIjpbIk9ubGluZVNob3AuQXBpIl19.Bl8FNIU8ckf2JAlKuREuEc-RDKhL_ur86SmRxf5E5yEIs1bUCNVTtyqsBzjPg0PVuugnhsTrvdHyUWJ-aySN5pe5Apc20byGVE0nQ--_PDz3ApZVPPsljuXiUyEQb7Z7QhJ7v67l2SsrIT4Jr6s0sfPR92DuPOUQss8ktrOH04NBlE0UK0hrnVA3izhKN6HSNAAmf_BNMVIXXmKE4sn9i_ciYL5PgprPqQ_wdszvz2C7tFx_tpRsdK3-dJpgY6gW-I_c_xXOzGmOJPLlhI93DbXyMI2kJQEmiV63jdybkwi5otWfdgwbk9nea9SCLpv3hDhyySrGpJhb-iwx2dVlqg