using OnlineShop.Library.Common.Interfaces;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace OnlineShop.Library.ArticlesService.Models
{
    public class Article : IIdentifiable
    {
        [Key] //primary key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //id must be generated by the database and must be unique
        [Column(TypeName = "uniqueidentifier")] //type of the column in the database
        public Guid Id { get; set; }

        [Required] //required: means that the field cannot be null
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        public ICollection<PriceList> PriceLists { get; set; }
    }
}
