GET https://localhost:5003/users?userName=yaroslav
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVCMTg0RTI3MDg5RTVFRDU2OTJFOTcyNjU2NjVDNkQyIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE3MDUyNDE5NzcsImV4cCI6MTcwNTI0NTU3NywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImNsaWVudF9pZCI6InRlc3QuY2xpZW50IiwianRpIjoiMDc4RjNEMDFCNDBFRTNDNDNFMDcxN0QyNjYwRjREN0YiLCJpYXQiOjE3MDUyNDE5NzcsInNjb3BlIjpbIk9ubGluZVNob3AuQXBpIl19.KEVhziXUxg107SPVll7HUozjsbkAq3ALYmrSlBFS3bO1qvhvAEv8FZnsm_pSS-ThcpSEJ-6QSn7dtPTt2zMVL637AAEmyRDCPsbVVrwRJu6VrPOsSbOsKRT8c7o_mQkDRqNbSaE9oN_0SETSaU-RpHNYjdi16YNhXO2ury2xtg-6CKKt0zN0I5eOIJddmpDZV2GQOMF1YricRB1eYfjKGMT4HxW5MJPvyomzl-8MTww-8YP8nDjST0kE7tEgjn_BjjzEeDYTyOh5A7XT2bIiEy9hMtkh5rQRPYEIJAhOkGaXvQ9HWuBtrIImZ6orM91SxRzrycA8GBSdxzlpX7eTtA