POST https://localhost:5006/pricelists/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVCMTg0RTI3MDg5RTVFRDU2OTJFOTcyNjU2NjVDNkQyIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE3MDQ2NTAzMzQsImV4cCI6MTcwNDY1MzkzNCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImNsaWVudF9pZCI6InRlc3QuY2xpZW50IiwianRpIjoiMEQ1QTgwNzcyMUQyOTM2OUE0Mjk5RURBRTEwRTg1QkQiLCJpYXQiOjE3MDQ2NTAzMzQsInNjb3BlIjpbIk9ubGluZVNob3AuQXBpIl19.t8z3ztBG3D4R0hEgytwtk81pkwoghMcM7VKfL3Y2pZh6TB3_7SIN-oZjx3TACnCwacaAQgWA-4SpaYagJjOcRrm5NJV2DJpTHwPJhaAhVqaGyPgjDOX-KqxCsY-r2w2Ppj8A7Wp77YPivejWrmsnBxSKK_sayB0TFxx4fbEGTSY9Je3BZQ468k02ZTwEjG-ewlSBAm5gVZ4Bg4r37rnB2iw36KLMNs0vXlsh7LDA9vYj7dlxB883N7uJdBN_Z2peBEeV96No3Y5Xa19kSCiI8O1-BO5ZTGW-eZH2NBYlqLmMhb6fDll9DfntH9NK0Lth3qjA31D9j18fP5l_xR_qWQ

{
    "id": "8657A746-A1A4-4039-EAEB-08DC20389C17",
    "articleId": "BA5D3BE3-6BDB-4167-DED7-08DC2032EFD5",
    "price": 500,
    "name": "Custom name",
    "validFrom": "2030-01-28T00:00:00",
    "validTo": "2035-01-28T00:00:00"
}

